from django.urls import path

from api.views import (
    InterventionView,
    OptimizationView,
    RecommendationView,
    RiskView,
    SelectedInterventionView,
    SimulationInitializeView,
    SimulationPauseView,
    SimulationResetView,
    SimulationResumeView,
    SimulationRunView,
    SimulationStateView,
    SimulationStepView,
    SimulationTeardownView,
    NowcastView,
    SimulationPresetsView,
    WorldZonesView,
    WorldSheltersView,
    WorldBoundsView,
    NavigationRouteView,
)


urlpatterns = [
    path(
        "simulation/initialize/",
        SimulationInitializeView.as_view(),
        name="simulation-initialize",
    ),
    path(
        "simulation/state/",
        SimulationStateView.as_view(),
        name="simulation-state",
    ),
    path(
        "simulation/step/",
        SimulationStepView.as_view(),
        name="simulation-step",
    ),
    path(
        "simulation/run/",
        SimulationRunView.as_view(),
        name="simulation-run",
    ),
    path(
        "simulation/pause/",
        SimulationPauseView.as_view(),
        name="simulation-pause",
    ),
    path(
        "simulation/resume/",
        SimulationResumeView.as_view(),
        name="simulation-resume",
    ),
    path(
        "simulation/reset/",
        SimulationResetView.as_view(),
        name="simulation-reset",
    ),
    path(
        "simulation/teardown/",
        SimulationTeardownView.as_view(),
        name="simulation-teardown",
    ),
    path(
        "simulation/risk/",
        RiskView.as_view(),
        name="simulation-risk",
    ),
    path(
        "simulation/recommendations/",
        RecommendationView.as_view(),
        name="simulation-recommendations",
    ),
    path(
        "simulation/optimize/",
        OptimizationView.as_view(),
        name="simulation-optimize",
    ),
    path(
        "simulation/intervention/",
        InterventionView.as_view(),
        name="simulation-intervention",
    ),
    path(
        "simulation/intervention/apply-selected/",
        SelectedInterventionView.as_view(),
        name="simulation-apply-selected-intervention",
    ),
    path(
        "simulation/nowcast/",
        NowcastView.as_view(),
        name="simulation-nowcast",
    ),
    path(
        "simulation/presets/",
        SimulationPresetsView.as_view(),
        name="simulation-presets",
    ),
    path(
        "world/zones/",
        WorldZonesView.as_view(),
        name="world-zones",
    ),
    path(
        "world/shelters/",
        WorldSheltersView.as_view(),
        name="world-shelters",
    ),
    path(
        "world/bounds/",
        WorldBoundsView.as_view(),
        name="world-bounds",
    ),
    path(
        "navigation/route/",
        NavigationRouteView.as_view(),
        name="navigation-route",
    ),
]
